version: "3.8"

services:
  db:
    image: postgres
    restart: always
    container_name: nodejs-pg
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pg-data:/pg-data

  node:
    container_name: node
    build:
      context: .
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
    ports:
      - "3000:3000"

volumes:
  pg-data:
