version: '3.8'

services:
  db:
    image: postgres
    container_name: nodejs-pg
    ports:
      - '${DB_PORT}:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nodejspg
    volumes:
      - ./pgdata:/var/lib/postgresql/data
