CREATE TABLE [IF NOT EXISTS] USER (
   ID INT PRIMARY KEY NOTNULL,
   firstname VARCHAR(255) NOT NULL,
   lastname VARCHAR(255) NOT NULL,
   email VARCHAR(255) UNIQUE NOT NULL,
   PASSWORD ENCRYPTED VARCHAR(255) NOT NULL,
   ROLE ENUM(length) NOT NULL,
   timestamp timestamp,
   table_constraints
);